version: '3'

services:
  composer:
    image: composer
    volumes:
      - ./app-src:/app
    working_dir: /app
    command: composer install

  php:
    build: ./php
    volumes:
      - ./app-src:/usr/src/laravel-docker
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
      - composer
    environment:
      APP_PORT: ${APP_PORT}


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
