version: '3'

services:
  php:
    build: ./php
    volumes:
      - ./app-src:/usr/src/laravel-docker
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-docker
